#pragma config(Sensor, in1,    liftPoten,      sensorPotentiometer)
#pragma config(Sensor, in5,    colorSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  leftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEnc,       sensorQuadEncoder)
#pragma config(Motor,  port1,           baserearright, tmotorVex393, openLoop)
#pragma config(Motor,  port2,           armMot,        tmotorVex393, openLoop)
#pragma config(Motor,  port4,           backHang,      tmotorVex393, openLoop)
#pragma config(Motor,  port6,           handliftr,     tmotorVex393, openLoop)
#pragma config(Motor,  port7,           handliftl,     tmotorVex393, openLoop)
#pragma config(Motor,  port8,           basefrontleft, tmotorVex393, openLoop)
#pragma config(Motor,  port9,           baserearleft,  tmotorVex393, openLoop)
#pragma config(Motor,  port10,          basefrontright, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////Global Variables/////////////////////////

int liftpotenmin=300;
int liftpotenmax=1600;
int thresold=20;

void baseControl()
{

	if(  (abs(vexRT[Ch2]) >thresold) ||   (abs(vexRT[Ch3])>thresold) )
	{
		motor[basefrontleft]=motor[baserearleft]=vexRT[Ch3];
		motor[basefrontright]=motor[baserearright]=vexRT[Ch2];
	}
	else if( (abs(vexRT[Ch2])<thresold) || (abs(vexRT[Ch3])<thresold) )
	{
		motor[basefrontright]=motor[baserearright]=motor[basefrontleft]=motor[baserearleft]=0;
	}
}

void moveLift()
{
	time1[T1]=0;
	if(SensorValue[liftPoten]>liftpotenmax-800) // if the lift is up then move the lift down
	{
		while(SensorValue[liftPoten]>liftpotenmin)
		{
			motor[handliftl]=motor[handliftr]=-50;



			if(time1[T1]>2000)
			{
				while(SensorValue[liftPoten]<liftpotenmax)
				{
					motor[handliftl]=motor[handliftr]=127;

					baseControl();
				}
				motor[handliftl]=motor[handliftr]=20; // may be changed after testing
				return;
			}



			baseControl();
		}
		motor[handliftl]=motor[handliftr]=0;
		return;
	}




	else if(SensorValue[liftPoten]<liftpotenmin+800) //  if the lift is down then move the lift up and leave
	{                          						          // the motors running with little power (40 will be altered after testing)
		while(SensorValue[liftPoten]<liftpotenmax)
		{
			motor[handliftl]=motor[handliftr]=127;



			if(time1[T1]>2000)
			{
				while(SensorValue[liftPoten]>liftpotenmin)
				{
					motor[handliftl]=motor[handliftr]=-40;

					baseControl();
				}
				motor[handliftl]=motor[handliftr]=0;
				return;
			}



			baseControl();
		}
		motor[handliftl]=motor[handliftr]=20; // may be changed after testing
		return;
	}
}

void handclose()//used to control the hands
{
	time1[T1]=0;
	motor[armMot]=100;	//close
	if(vexRT[Btn8L]==1)
	{
		baseControl();
		moveLift();
	}
	while(time1[T1]<50){}
	baseControl();
	motor[armMot]=0;
}

void handopen(){
	motor[armMot]=-127;  //open
	if(vexRT[Btn8L]==1)
	{
		baseControl();
		moveLift();
	}
	while(time1[T1]<50){}
	baseControl();
	motor[armMot]=-30;
}

void hanging()
{
	if(vexRT[Btn7U]==1 && vexRT[Btn7D]==0)
	{
		time1[T1]=0;
		while(time1[T1]<150){}
		if(motor[backHang]!=0)
			motor[backHang]=0;
		else if(motor[backHang]==0)
			motor[backHang]=127;
		///////////////////////////////////////////////////////////////
		//		while(SensorValue[colorSensor]>700)
		//		{
		//				motor[backHang]=127;
		//				baseControl();
		//				while(vexRT[Btn5D]==1)
		//  				handclose();
		//  				while(vexRT[Btn5U]==1)
		//  				handopen();
		//  				if(vexRT[Btn8L]==1)
		//   				 moveLift();
		//		}
		////////////////////////////////////////////////////////////
	}

if(vexRT[Btn7D]==1 && vexRT[Btn7U]==0)
{
	time1[T1]=0;
	while(time1[T1]<150){}
	if(motor[backHang]!=0)
		motor[backHang]=0;
	else if(motor[backHang]==0)
		motor[backHang]=-127;
}
}

task main()
{
while(1)
{
	baseControl();
	if(vexRT[Btn8L]==1)
	{
		moveLift();
	}
	while(vexRT[Btn5D]==1)
		handclose();
	while(vexRT[Btn5U]==1)
		handopen();
	hanging();
}// end of while

} // end of main
